### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kosh04** [kosh04/emacs-wandbox#12]
## Features

- [ ] Configure response-data
- [ ] Multiple files
- [ ] Easy setting for compiler options
- [ ] Selectable compiler in `wandbox-list-compilers`
